---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: my-nginx-site
spec:
  encryptedData:
    DB_PASSWORD: AgCPSqKFJxHtn+JzVhZbdFVVnGMU3NYU7vs81kxMVkICS6wChGo8UbQ5ijF4du/yeVMcYFac0i2+h7TBfGXvDqsWNEf45322V1HkLt9zmND3LvQX025tQr/iAG17Fx1wMmoRWWVCHZ77Euow0G100/xPeooSO64nd72plA3N7aW4O502IJ0F3rLu9r6lcLkRxRHKa6Q6ri3/msIoRXBAzMQiWIDIEVdzAEHbzPjvsMcAx8N2Nx1nHKx+BwzBsV0ByjiGzwiR5pZHjN8nyeqz2IVtS0kTEsNrXQxic2l3in8xC6YBClaxaN0xKHiNBtH7Kbv7BAj5pMhEp/kjAN66SW+a+jHJTTSLLFbIdvqbG3CRafxpmAOKzKnfbDk3UaOjg0EmFp44XgpSJqzVoV8yU3aVHwvD+0kqmdn+qEzhODGLoNvmBKUezs7E1/ZqRoj7K+RwN/rvHOO9FdTbFSoVdruBTI02e0ltLxr6Rs2mZfKIQRFvzHF+IKCBT4scmZSjjZ5bCKZkVSJlV7hMD0qxO5QeR0tQKVTa1dOOoKn2XdJKNb1gK4aLVgBu3TwdRR6LcbmiJrhJEwxz50sWxpO1y137N/i9AZcEqHZL3LYAdC91ejX/5rTnpRjsMIIZ6MuhNBprezHh3LJKZjWGxCpN3OeHEyXFZzR1/JnLA2SzeNxhZDTU4UKCj82gAw5zL7syhIaoU2b1nKh1jIgscQADKvc=
    POSTGRES_PASSWORD: AgAtxkoXsVwlF7c0w1D0zvQVtkPoAocat7XCfAxye9l1/OUYOAxcv/XAyJySlNeIdEuCkgDIFC4TeD7JWJk9CmajKIl/+M/0zLzIqAU7wtL+0qeT/C3Ud5ouzjt2D/NexpZiLljZXjeVXkkaBKDe/XHucBvzgjM/AEC6RM3f06/MiyAR11omiHZjuLI0hCKtgJYJxbqjn07lfl6dVHKLpOwqKnc6JLioO1IUo5fQ2SpENAMVGn7qHftD6D+HkmhdK67TGXTQFQ2geZvrZ+hlNRw4Xe8MIsa0tenDhKH9XE+V9pskpft6NN8rG3WOET507Bs23CxEhyLG3jQH29BY79nMcvPaEDB6S0Bs1Rwr01aX+QiqXQWyKO3TeR+RhcKoelWSvZ5XUvWiwycC+bnPJxvXD6B557NAyOrmqnPZksojJK4FOzaG+GDiN4S24PfOsuLso/ya4SxU9JUehN3YGgdOmrj+pv7v0NNXsmdKi1/xifZ+lQ+XbO2P6N1FMtTcJ0lDjfoatkoEjcq1JZ9VUxBIxBYo19t0X64kZbjzqjD24x1kuhAdYZCsbtaXwtX9jOAfIJOzcC3WZOPUfSngEoPPC1oBkJB7Dv6p8sjVJfK0PVKr2OWOHF909vMF0HxEklTnjUJFmFOHn9c+VwXCqwQZRurHjTxD81oIR+/TTLDdg0EsRxET9jaFjQJ8B+AjaZQ+tg44PfixxsMAlRwzihk=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: my-nginx-site
    type: Opaque
