---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-s3-secret
  namespace: my-nginx-site
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCBEJXDh1IT2NVJIlwtc4BpIo3AzY+BIB7nYRtuRBAIWO/XrUf48zSbYbpSuz+sqRdJ1aK9CcYi2KJxDt2n1+7D1qwaoFe1Ac3H3EvDGV0s8Oxx+UcZloh4IC+lii9OdAhm/ycUDGrP7OirYVDi/qGZStJDLuiCdIUULwQrGZ6wWbsT4OYyOGoTwCIrdHZ0gdZN1OxCp5+Kv+Z1ljjc/EJlaNkEh13huUEBPIlxw1VPTrLJmGT1bBPVyzK9hkMxU9MC7o3D5aFg+Plesl/epwDcNh1oSMTg5r9FwodVk5AbuUT20CpvasSLE+8u43fg6FAFoEZOINiaeMaWLMSrR4irSfjUm81TFgzkgx7ebtbeiru/mpqB4SAg03LnhZU3bHQp4NPLa7WYC0ViqKr/MadtV9kCwHBBcRpsMcYtoMjqXwDji1Lr3Ek/vklKJaQHho1V8PtIhDxJcaRg1hJcNl9TLTQ131SIA57fIZv//b8szqOL2lOb0qhyOrHw0zjtlmh+SuB/s/5yBQuyxRRRv/QO1l1tY42sixXgz4anzbtGIIup3s7Mye3FwXVBxVUxKzlgmgFtAg4DaXrCZTBxrgkJUes5z6rKYKUj4FGskuBodjOfwaLWh4utd/eFHnNj7SkdPkEPhl6a3ihHiD4RxVsM5xu8JawMK8SKCG4vJAfJ+mTMzhI7EH0cFU3umUH1IOF6xlO5sqalVPSKGQyqlW22NsFV06m5RmeA
    AWS_SECRET_ACCESS_KEY: AgCWSmIs1F4fvxmKXOOmU4Q7sDVYJ9UstT5K85uN+R05lBhdmvvMMyHT/xfaA1UWf+gLw67aq3sq2c1dvuEllqMYcCt6q0ksrnlRO4vr/c9xF3gqAZTrYBLn457hFcAphCjllX87Wv44Gzmh7iR1rbcw+DyE5JSHrb/n5pk8jE6r4514ZR9rbKs2dJnEp6DJVxFbXWu7qbL11yKWu2f1mmz8kXj6Qff1XKyl7jBIJMKQ4oEkpqg/vGT61zxD5++qf7SpBHE+oHBwml4jxc8UprXFdVFYs1Uc7XPCk/pAk6ao6F4fkiWdpGzL3FytHb9fODXeEvID34CbhR+D3AkJXY/THxON69w7MTIaNgiRW5ZFInmTUVmKkPUViTBZ3OjsPzJZswQmw/EYjpH6GuGxL6Ak/mJr8WMK8vhbxOrDdk7Zaa5dPziDUmQKplSMdC0BgwTIk7JLHy6vMIWNzvj4BBGug0V6t58he+jPMN6eXtHzrz3GtLg4Yj4NiHJg//3u/EEEdIuVLeEOxPKhU2fu9SJkHnUbSk3PWrOL4oklVXFlAIKWIfADUk3mn9WnniOGy0cfl3jWFEDJnMNKm7Q+WJsZRk70t6qFQWD62NurXdjkUcYdo5DJMsD3xF8IfG83lF7IoRx0I/WmfkplQS3/Eb8/SKKQKJN1W/73h5rM0//E2UGMUGXEfDpFIgIdLiJdJsEgjKSTl3EE5AKDl+lbjtsZJ9Z4tdEyk81R0/v1zTaOOEMO6frZ14JD
  template:
    metadata:
      creationTimestamp: null
      name: backup-s3-secret
      namespace: my-nginx-site
    type: Opaque
