apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: my-nginx-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: cr.yandex/crpk5978o767co0bur2k/site:sha-9d291ff
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "200m", memory: "128Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: my-nginx-site
spec:
  selector:
    app: site
  ports:
    - port: 80
      targetPort: 80

